name: eizo_mushi
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  chewie: ^1.11.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  smooth_page_indicator: ^1.2.1
  video_player: ^2.9.5

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
